version = 0.1

[default]
[default.build.parameters]
cached = true
parallel = true
[default.deploy.parameters]
stack_name = "S3-Deploy"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "S3-Deploy"
region = "eu-west-2"
parameter_overrides = "OrganizationID=\"False\" ouID=\"False\" useDatabase=\"False\""
image_repositories = []
